on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: knit-cv

jobs:
  knit-cv:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: render the curriculum vitae
        run: |
          Rscript -e "rmarkdown::render(here::here('cv.Rmd'))"

      - name: generate pdf
        run: |
          Rscript -e "pagedown::chrome_print('cv.html')"

     - name: commit cv
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add the cv.pdf file to the 'docs' directory of the repository"
          git push
     - name: Upload cv
       uses: actions/upload-artifact@v1
       with:
         name: docs
         path: docs/
